### PR TITLE
Create zh_CN.lang

### PR DESCRIPTION
**Pull request by Joccob**

### CODE REVIEW

**Comment by ScottKillen** [comment]
@Joccob,

I noticed here that you have substituted common woiod names for the unique names I chose (Larch for Acemus, etc.)

It there a way to preserve the unique names in Chinese? The names were chosen with a purpose that is thwarted by using common species names.

**Comment by Joccob** [comment]
I will try to make them unique. U said the names were chosen with a purpose, would u mind telling me where they comes from? A book, a game or an old stroy.  And I also want to know what language are those names based on? Latin or some other lang? It will helps a lot if you can give me all the info.

Anyway, thanks for making such a great mod.

**Comment by ScottKillen** [comment]
Some are loosely based on trees and colors in Latin and several other obscure languages. Some are made up. 

The goals are to seem ancient and mysterious and to sound like the names *could* have an etymology that is plausible but not attributable to any particular species. At least one fails in this regard.  :grinning: You have an opportunity to be creative here. 

Thanks for the positive feedback and the contribution of your time and work!

**Comment by ScottKillen** [comment]
The work on this seems to have been discontinued.

**Pull request closed without merging**
